### ISSUE TITLE
iface_utils.cc: wrong applied assertion on ioctl calls

### ISSUE THREAD

**Issue by toanju** [bisdn/xdpd#43]
adding veth interfaces and moving one of them into another namespace leads to this assertion [iface_utils.cc#L67](https://github.com/bisdn/xdpd/blob/31355d3af1d627b933aac4967f601091cd1653b7/src/xdpd/drivers/gnu_linux/src/io/iface_utils.cc#L67)

reproduce with a script like:
```bash
ip netns add NETNS
ip link add OUTER type veth peer name INNER
ip link set INNER netns NETNS
```

**Comment by msune** [comment]
#41 relies on being able to make ioctl commands and ethtool ones to disable certain offloads. 

The assertion _could_ be removed, provided that an approriate error message is `ROFL_ERR`.

The fundamental problem is, with the limitations of the `mmap` and veths, if you cannot access the veth peer to automatically disable some offloads, this can be quite a problem. Is there someway to access to the global namespace (we have root privileges, ofc)?

**Comment by toanju** [comment]
In first place this has nothing to do with #41, possibly this assertion will happen as well, if you rename the interface asap, thus the name used here is gone.

Since the fix is already applied I will close this now.

**Comment by msune** [comment]
Well, this `assert(0)` was there to indicate, as you comment in a private mail, that effectively the disabling of offloads for the pair veth does not work if the ioctl here checked. So yes, it is related **very** related to #41.

We can open another issue if you want, but commenting this assert was not a bug... the fact that the offloads of the pair veth interface cannot be disabled, due to being in another namespace, and that this is a requirement to not have problems with the kernel not calculating (`TP_STATUS_CSUMNOTREADY `), **is** the issue and needs to be fixed.

So feel free to either open another issue or continue here.

**Comment by toanju** [comment]
as mentioned above another way to reproduce this race condition is to rename interfaces:

```bash
ip link add type veth;ip link add type veth; ip link set veth4 name asdf; ip link set veth5 name qwer;
```

the bug mentioned in the private mails was never intended to go here, this is now in #44
