### ISSUE TITLE
handling offloads of peer veth in another namespace

### ISSUE THREAD

**Issue by toanju** [bisdn/xdpd#44]
#41 added offload handling for veth pairs. xDPd therefore has modified the offload behavior of both both interfaces of the pair. If the peer interface is moved into another namespace the current solution does not work any longer.

There are two options to solve this:
1. only change the local interface attached to xDPd
2. check if the peer interface is running in another namespace and change the offloads

**Comment by toanju** [comment]
if we go for 1. then the peer interface offloads have to be set by the party using that interface

**Comment by msune** [comment]
I would go for 2; the limitation of the offloads is due to the way the gnu-linux driver accesses the interfaces (PF_PACKET MMAP), and the user should not be aware of these details in general.

Other drivers, e.g. DPDK, OCTEON... don't impose requirements beyond the normal configuration of xDPd, and any detail is handled at the level of the driver. I think we should continue with this approach
